language: ruby
sudo: false
cache: bundler
rvm:
  - 2.2.0
  - jruby-19mode
services:
  - redis-server
jruby_before_script:
  - bundle exec jbundle install
addons:
  code_climate:
    repo_token:
      secure: YL7mBXUP07n+gybTpteIWwHg/hUbJns1Q/O+pdsphrbD54ikKPI1Frir1woLPdyrPYSJ3jUiQNbBjy8lTope7DH+SI7JsUV2vjPDKUfnb+VsCD/KI9UxIAt5e1NkdIgDFSZHj9Qh3vOw6/8X+mQ9mh0Nlwhicjb146IXfG73XjM=
